import Head from 'next/head';
import { GetStaticProps } from 'next';
import { Flex } from "@chakra-ui/react";
import { api } from '../services/api';

import { Header } from '../components/Header';
import { Banner } from '../components/Banner';
import { TravelTypes } from '../components/TravelTypes';
import { Slider } from '../components/Slider';

interface Continent {
  id: string;
  name: string;
  slogan: string;
  description: string;
  countries: number;
  languages: number;
  banner: string;
}
interface HomeProps {
  continents: Continent[];
}
export default function Home({continents}: HomeProps) {
  return (
    <Flex direction="column" h="100vh">
      <Head>
        <title>worldtrip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner />
      <main>
        <TravelTypes />
        <Flex 
          w={["100%", "1440px"]}
          px={[0, 100]}
          my={5}
          mx="auto"
          h={["250px", "450px"]}
        >
          <Slider 
            continents={continents}
          />
        </Flex>
      </main>

      <footer>
        
      </footer>
    </Flex>
  )
}

export const  getStaticProps: GetStaticProps = async () => {
  const { data } = await api.get('continents');
  const continents = data;

  return { 
    props: {
      continents,
    },
    revalidate: 60 * 60 * 8,
  }
}